{
 "title": "security Issues Projekt Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Backend average response time",
   "type": "graph",
   "description": "Average response time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_sum[5m]))/sum by (uri)(rate(http_server_requests_seconds_count[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Frontend average reponse time",
   "type": "graph",
   "description": "Average response time of the frontend server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (path)(rate(http_request_duration_seconds_sum[5m]))/sum by (path) (rate(http_request_duration_seconds_count[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Frontend node memory usage",
   "type": "graph",
   "description": "Shows memory usage of the node web server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{service=\"react-frontend\"} / 1024 / 1024",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{service=\"react-frontend\"} / 1024 / 1024",
     "legendFormat": "Total heap"
    },
    {
     "expr": "nodejs_heap_space_size_total_bytes{space=\"new\",service=\"react-frontend\"} / 1024 / 1024",
     "legendFormat": "Total new space"
    },
    {
     "expr": "nodejs_heap_space_size_used_bytes{space=\"new\",service=\"react-frontend\"} / 1024 / 1024",
     "legendFormat": "Used new space"
    },
    {
     "expr": "nodejs_heap_space_size_total_bytes{space=\"old\",service=\"react-frontend\"} / 1024 / 1024",
     "legendFormat": "Total old space"
    },
    {
     "expr": "nodejs_heap_space_size_used_bytes{space=\"old\",service=\"react-frontend\"} / 1024 / 1024",
     "legendFormat": "Used old space"
    }
   ]
  },
  {
   "title": "Quarkus Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"} / 1024 / 1024",
     "legendFormat": "Used heap"
    },
    {
     "expr": "jvm_memory_committed_bytes{area=\"heap\"} / 1024 / 1024",
     "legendFormat": "Committed heap"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"none-heap\"} / 1024 / 1024",
     "legendFormat": "Used non-heap"
    }
   ]
  },
  {
   "title": "Backend Error Rate",
   "type": "graph",
   "description": "Percentage of HTTP 5XX responses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5.*\"}[5m]))/sum(rate(http_server_requests_seconds_count[5m])) * 100"
    }
   ]
  }
 ]
}